### ISSUE TITLE
Memory Releasing issue

### ISSUE THREAD

**Issue by nathanjsweet** [nathanjsweet/nodehun#13]
For Someone named Matt:

Hi, Nathan,

I'm working on a node.js-based spell-checking service and was delighted to stumble upon [1]. Thanks for creating/maintaining this hunspell binding.

I'm running into an issue, on my Mac (OSX Yosemite) where the node.js process crashes with 'Segmentation fault: 11' randomly after as few as 11 HTTP requests and up to ~100 HTTP requests.

If I cache a single nodehun instance and reuse that, I can run my test suite (contains ~5500 inputs) repeatedly.

Alas, the requirement of the service is that it can accept requests for various combinations of dictionaries and word lists, so I'll likely need to create a custom instance for many requests (I can probably employ some caching).

My pattern for instantiating nodehun which produces the results above was that shown in examples/a_init.js (new nodehun(aff, dict)).

I modified the code to use the pattern in g_asyncinvoke.js, and that's producing the following:

node(10787,0x103c8d000) malloc: *** error for object 0x104039008: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

In an attempt to simplify / make the problem more easy to repo, I've attached a modified version of the g_asyncinvoke.js example. It looks like the issue (hopefully equivalent to what I'm seeing in my service) can be reproduced after ~35 iterations.

FWIW, I'm using 64-bit node v0.10.33.

Please let me know if I can provide additional info. I can also take this to [2] if you prefer.

Regards,
Matt

Relevant file: https://docs.google.com/document/d/1qamzmStKEogJI3ybaJKNgT8xLiSCc2JdWAnJ-3CFk-c/edit?usp=sharing

**Comment by nathanjsweet** [comment]
Matt,
I'm not on Yosemite, yet, I will update later to check this out. I'm hoping that you plan on deploying on a linux server. If that's the case, then I would say you shouldn't have to worry about this issue (I've tested this script on several linux boxes and they all worked fine).

This is going to sound like a cop out, but OSX sucks. I run into all sorts of memory and segmentation issues that just don't crop up on linux (32 bit or 64) or even windows (again 32/64). I have personally played around a lot with libuv on my macbook and my impression of the teams for it, v8, and nodeJS is that apple is an afterthought for them.

For example, there are many hacks out there to get node to work around the 256 file-descriptor per process limit on OSX, but nobody has bothered to include any of these into libuv or node.

I'm going to mark this issue as closed for now. If this ever becomes an issue on linux or windows let me know.
Thanks,
Nate

**Comment by mattoshry** [comment]
Fair enough, Nate.

OSX has been a decent dev platform, but deployment will be on Linux. Will keep an eye out during perf / load testing on target OS.

Best,
Matt

**Comment by nathanjsweet** [comment]
Matt,
Have you noticed any problems on linux?
