### ISSUE TITLE
Charset suggestions error

### ISSUE THREAD

**Issue by peraferrer** [nathanjsweet/nodehun#16]
Hi, we are using nodehun with dictionaries (es_AR.aff, es_AR.dic) and when suggestions are generated, words with spanish accents are displayed weird.

We tried changing the charset file (es_AR.aff, es_AR.dic) and have no luck. Also, we changed the charset for each word from suggestions array, and it didn't work neither. 

Finally, we set the charset in the response header and we have the same result. 

To clarify, "version", suggestion should be "versión", and in the suggestion array we found "versi?n":

{
     word, 'version',
     suggestions: ['versi?n'],
     positions: [[Object]]
}

Could you bring some help? Are we missing something?

Thank you very much.

**Comment by nathanjsweet** [comment]
I am busy this week, I'll try to get to it this coming weekend. Thanks for your patience, and I'm sorry it isn't working for you.

**Comment by nathanjsweet** [comment]
So I downloaded the es_AR.dic and es_AR.aff files and noticed that they were being served blindly as UTF-8, even though they were actually encoded ISO-8859-15, so I just converted them to UTF-8 (which you have to do for javascript, and, I think hunspell). Anyways, after I did that they worked perfectly. If you have `inconv`, which you should on any *nix system, then you can simply run the following command to convert them:
```
iconv -f ISO-8859-15 -t UTF-8 es_AR.aff > es_AR.conv.aff
```
If you're still having issues, let me know and I can email you the dictionary files that I converted. Hope that helps!

**Comment by peraferrer** [comment]
Thanks Nathan, it worked perfect, I also needed to convert the .dic file.

A hug.

**Comment by nathanjsweet** [comment]
You're welcome! Right back at you :)
