### ISSUE TITLE
Nodehun not compatible with node 0.12 and iojs

### ISSUE THREAD

**Issue by rexxars** [nathanjsweet/nodehun#19]
I can't seem to build nodehun on node 0.12 and iojs.
I'm guessing this is because of an updated V8?

**Comment by nathanjsweet** [comment]
Yeah, I'll be getting to this soon (hopefully this weekend or next).

**Comment by nathanjsweet** [comment]
this is done

**Comment by rexxars** [comment]
Cool. I don't mean to offend in any way, but have you considered using https://github.com/rvagg/nan for abstracting the differences between versions?

Right now it's hard to depend on this project because basically we will be forced to follow the same scheme as you, requiring a given version of node for a given version of our modules.

**Comment by nathanjsweet** [comment]
This is a not to myself:
https://github.com/rvagg/nan/blob/master/nan.h
I'm going to use node_version.h to build the two different versions based on using ifdef pragmas in the compiler.

**Comment by nathanjsweet** [comment]
I'm not using NAN, but users shouldn't have to worry about versions anymore

**Comment by rexxars** [comment]
Thanks Nathan, that's great! Thank you for your hard work 👍
