### ISSUE TITLE
Question: Could Nodehun performance increase if there was a Readonly Dictionary Option?

### ISSUE THREAD

**Issue by jtemplet** [nathanjsweet/nodehun#22]
I was looking at the Nodehun binding code and noticed that in Nodehun::SpellDictionary::checkSuggestions() it sets a lock on the dictionary - before it looks up the word. 

In my case, I'm only using the dictionary as read-only, it never changes. So if the dictionary never changes, technically, we don't need a lock on the dictionary and theoretically improving performance.

What I was thinking was that I could provide an option to make the dictionary read-only when you create the dictionary object and then you can just put an if-statement around the locks.

Thoughts? 

Jason

**Comment by nathanjsweet** [comment]
If you look carefully you'll see that it's a [readwrite lock](https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock), which means that if all you're doing is reads then the lock won't do anything.
