### ISSUE TITLE
Why shouldn't we use readFileSync() ?

### ISSUE THREAD

**Issue by letunglam** [nathanjsweet/nodehun#23]
I'm a newbie to nodejs, so please forgive if I ask things that are painfully obvious.

I read the document and I don't know why we shouldn't actually use readFileSync and is there any better solution to read dictionary file? 

Any help or example, references would be highly appreciated.

**Comment by nathanjsweet** [comment]
So, it's fine to use readFileSync if you are doing it on initialization of your program. If you are doing it a lot throughout the lifetime of your program than you are blocking the main thread unnecessarily and should seek to use the non-blocking readFile function. 

To understand this paradigm and its history better try googling around to understand what it means when people say that Nodejs is non-blocking.
