### ISSUE TITLE
Synchronous spell checking 

### ISSUE THREAD

**Issue by astoilkov** [nathanjsweet/nodehun#26]
Is there any way to make a synchronous spell check? The problem I am having is that I am using Atom/Electron platform to built cross platform desktop application and their requirement is to use synchronous spell checking.

Here is the code from their [documentation](https://github.com/atom/electron/blob/master/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-autocorrectword-provider):
```javascript
require('web-frame').setSpellCheckProvider("en-US", true, {
  spellCheck: function(text) {
    // return true or false
  }
});
```

You have done amazing job with this library and I would really like to use it. Keep the good work.

**Comment by astoilkov** [comment]
Another approach will be to introduce a synchronous method that just returns true/false if the word is correctly spelled.

**Comment by erusev** [comment]
I'd also like to know that, thanks.

**Comment by nathanjsweet** [comment]
Sorry for the late reply. I will try to get to this soon, and it relates to #25 anyways. I am nearing the end of taking a few weeks off for personal reasons. When I am back in action I will create synchronous versions of all the methods.

**Comment by astoilkov** [comment]
I got really excited when I saw your response. I can't wait to try out the synchronous spellchecking in action.

Happy coding.

**Comment by erusev** [comment]
@nathanjsweet That's great! Thanks for the prompt response and I look forward to the new methods.

**Comment by astoilkov** [comment]
Hi Nathan,

What is the status for this issue? We really want to use nodehun as our spell checking library. We are building Desktop application using Electron. We are working on the final touches for our application and we were wondering if you are going to be able to implement these methods.

**Comment by nathanjsweet** [comment]
I am currently working on it still. I will try to get it out by the end of this week.

**Comment by astoilkov** [comment]
This is great news. Thanks a lot!

**Comment by nathanjsweet** [comment]
Done 428a262756652caf31358185cc50e8af457fc97d

**Comment by erusev** [comment]
@nathanjsweet Thanks!

**Comment by astoilkov** [comment]
Hi,

I just finished the initial implementation of the spell checking in our application. The library worked flawlessly. Thank you very much for your effort.

Have a great day.

**Comment by nathanjsweet** [comment]
Are either of you interested in taking over this project?

**Comment by astoilkov** [comment]
This is great project. However, we are not familiar with C++ programming and we can't help the project. Sorry. :)
