### ISSUE TITLE
Compilation errors on Travis (Linux)

### ISSUE THREAD

**Issue by wooorm** [nathanjsweet/nodehun#27]
Hey @nathanjsweet,

First off: great project, thanks a lot!
Second: I just created a lot of easily insoluble [dictionaries](https://github.com/wooorm/dictionaries), maybe useful for the other nodehun users (or the README?)

And third, I’m getting compilation errors on Travis when building on Node 0.10, 0.11, 0.12, `iojs`, and 4.0. They seems to be related to nodehun rather than my module. Here are the logs: <https://travis-ci.org/wooorm/retext-spell/builds/81763026>. Also interesting: there’s a difference between the old node versions (e.g., [0.12](https://travis-ci.org/wooorm/retext-spell/jobs/81763029)) and new versions (e.g., [4.0](https://travis-ci.org/wooorm/retext-spell/jobs/81763031)).

I’m hopeful that you can shed some light on these errors! Thanks!

**Comment by nathanjsweet** [comment]
I'll take a look.

**Comment by wooorm** [comment]
Thanks @nathanjsweet!

**Comment by nathanjsweet** [comment]
Titus, you are getting compilation errors for iojs and 4.0, as I have not yet updated nodehun to conform to their new C++ api. However, you are **not** getting compilation errors on the other versions. It looks like your tests are running and a test of yours is [failing](https://github.com/wooorm/retext-spell/blob/master/test.js#L146). I downloaded your en_GB dictionary and tried passing the same string to `spellSuggestions`, which it looks like what [you are doing here](https://github.com/wooorm/retext-spell/blob/master/index.js#L51), and it worked fine for me (I definitely didn't get the malloc error you're seeing). 

It looks like you're doing some complicated stuff like abstracting strings into objects. Could it be that your `VFile` or `NLCSTNode` objects have some undefined behaviors around odd UTF-8 characters?

I'm closing unless you have new information for me that I'm not seeing.

Hope this helps. Good luck!
