### ISSUE TITLE
Update nodehun to conform to new iojs and nodejs 4.0 C++ api using NaN

### ISSUE THREAD

**Issue by nathanjsweet** [nathanjsweet/nodehun#28]
Currently nodehun does not build for iojs or nodejs 4.0. The only acceptable fix is to migrate to [NaN](https://github.com/nodejs/nan).

**Comment by nathanjsweet** [comment]
For bug bounty-hunters. Here are some rules:
1. You have to do this with NaN
2. The documentation and code-style must conform to the style found in this repository's code.

**Comment by digitalhobo** [comment]
Hi Nathan
Did you manage to get it to work with the migration.

**Comment by nathanjsweet** [comment]
Hey digitahobo, I have this as an open issue, but I am no longer actively maintaining this repo.

**Comment by digitalhobo** [comment]
Thanks for getting back to me, I managed to get it working. The problem I had wasn't and issue with module but rather a error while loading shared libraries. It working a treat.
Thanks again - great work. :0)
