### ISSUE TITLE
npm install failed on windows 7

### ISSUE THREAD

**Issue by kmsheng** [nathanjsweet/nodehun#29]
Hi ! Thanks for maintaining this project, but I got a little error when doing npm install.

245 error Windows_NT 6.1.7601
246 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodehun" "--save"
247 error node v0.12.7
248 error npm  v2.11.3
249 error code ELIFECYCLE
250 error nodehun@2.0.8 install: `node-gyp rebuild`
250 error Exit status 1
251 error Failed at the nodehun@2.0.8 install script 'node-gyp rebuild'.
251 error This is most likely a problem with the nodehun package,
251 error not with npm itself.
251 error Tell the author that this fails on your system:
251 error     node-gyp rebuild
251 error You can get their info via:
251 error     npm owner ls nodehun
251 error There is likely additional logging output above.
252 verbose exit [ 1, true ]
253 verbose unbuild node_modules\nodehun
254 info preuninstall nodehun@2.0.8
255 info uninstall nodehun@2.0.8
256 verbose unbuild rmStuff nodehun@2.0.8 from C:\Users\alice\Downloads\test\node_modules
257 info postuninstall nodehun@2.0.8
258 silly gentlyRm C:\Users\alice\Downloads\test\node_modules\nodehun is being purged from base C:\Users\alice\Downloads\test
259 verbose gentlyRm don't care about contents; nuking C:\Users\alice\Downloads\test\node_modules\nodehun
260 silly vacuum-fs purging C:\Users\alice\Downloads\test\node_modules\nodehun
261 silly vacuum-fs removing C:\Users\alice\Downloads\test\node_modules
262 silly vacuum-fs finished vacuuming up to C:\Users\alice\Downloads\test

**Comment by josephrocca** [comment]
Very late answer, but I see a `node-gyp` error in there, so if that's the root of the problem, then here's the solution:

https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

I had the same problem when installing this library on Windows 10.

**Comment by nathanjsweet** [comment]
I am no longer maintaining this project
