### ISSUE TITLE
Installation fails on Travis for node versions 4+

### ISSUE THREAD

**Issue by zaccolley** [nathanjsweet/nodehun#30]
I have a test repo with just nodehun in at 2.08: https://travis-ci.org/zaccolley/nodehun-travis-test

It works locally when I use 5.0.0 which is why I'm confused.

Will continue to try find the issue but opening here if anyone knows.

**Comment by nathanjsweet** [comment]
I am no longer maintaining this project

**Comment by nathanjsweet** [comment]
fixed #32
