### ISSUE TITLE
Not compatible with NodeJS 6

### ISSUE THREAD

**Issue by theolagendijk** [nathanjsweet/nodehun#31]
**node-gyp rebuild** ( part of **npm install nodehun** ) fails on system with latest versions of **NPM** and **NodeJS**.

**Comment by nathanjsweet** [comment]
I am no longer maintaining this project.

**Comment by theolagendijk** [comment]
sorry to hear that. thanks for the nodehun project!

**Comment by Wulf** [comment]
I've fixed this in my fork [here.](http://github.com/Wulf/nodehun)

This should work:

`npm install wulf/nodehun`

I'll try to get in touch with @nathanjsweet.

**Comment by nathanjsweet** [comment]
fixed #32
